version: '3.7'
networks:
  <yourNetwork>:
    external: true

volumes:
  prometheus-data: {}
  grafana-data:
    driver: local

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    depends_on:
      - prometheus
    networks:
      - <yourNetwork>

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=40d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    environment:
      TZ: 'Europe/Rome'
    ports:
      - 9090:9090
    networks:
      - <yourNetwork>

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0 # latest tag is not updated...
                                            # https://github.com/google/cadvisor/issues/3066    
                                            # To manual check versions: https://github.com/google/cadvisor/releases      
    container_name: cadvisor
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - <yourNetwork>

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      TZ: 'Europe/Rome'
    restart: unless-stopped
    networks:
      - <yourNetwork>