server:
  http_listen_port: 9080
  grpc_listen_port: 9111     ### to edit in different machine 

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push     ### to edit in different machine

scrape_configs:
# docker logs
- job_name: docker
  pipeline_stages:
    - docker: {}
  static_configs:
    - labels:
        job: docker
        #host: <hostname>     ### to edit in different machine
        __path__: /var/lib/docker/containers/*/*-json.log
# local machine logs
- job_name: local
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

# syslog target

#- job_name: syslog
#  syslog:
#    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#    idle_timeout: 60s
#    label_structured_data: yes
#    labels:
#      job: "syslog"
#  relabel_configs:
#    - source_labels: ['__syslog_message_hostname']
#      target_label: 'host'